[tool.poetry]
name = "st-undp"
version = "0.1.0"
description = "A utility package that styles Streamlit apps according to UNDP Design System"
authors = ["Mykola Skrynnyk <mykola.skrynnyk@undp.org>", "Gedion Disassa <gedion.disassa@undp.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.38.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
