name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: st-undp
  PYTHON_VERSION: '3.11'

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install

      - name: Export requirements.txt
        run: |
          poetry export -f requirements.txt -o requirements.txt --without-hashes

      - name: Add startup.sh
        run: python -m st_undp configure --settings deployment

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            .
            !venv/  # Exclude the virtual environment if it exists
  
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
